# Generated by Django 5.0.7 on 2024-08-27 15:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=50)),
                ('nom', models.CharField(default='nom', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fabricant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='fabricant')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(default=datetime.datetime(2024, 8, 27, 15, 52, 54, 896912, tzinfo=datetime.timezone.utc))),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client.client')),
            ],
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(default='contact', max_length=20)),
                ('adr', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=50)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('prix', models.FloatField()),
                ('reduction', models.FloatField(default=0.0)),
                ('image', models.ImageField(upload_to='medicament')),
                ('domaine_application', models.TextField(null=True)),
                ('info', models.TextField()),
                ('description', models.TextField()),
                ('zone_traitement', models.TextField(null=True)),
                ('arte', models.CharField(max_length=50, null=True)),
                ('exemple_lien_bout', models.CharField(max_length=50, null=True)),
                ('fabricant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client.fabricant')),
            ],
        ),
        migrations.CreateModel(
            name='Ligne_commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_cmd', models.IntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.commande')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client.medicament')),
            ],
        ),
    ]
