# Generated by Django 5.0.7 on 2024-08-28 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_heure',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 28, 10, 51, 52, 92241, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='arte',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='domaine_application',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='exemple_lien_bout',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='zone_traitement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
