# Generated by Django 5.0.7 on 2024-08-29 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_medicament_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='est_livre',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_heure',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 29, 15, 55, 26, 706126, tzinfo=datetime.timezone.utc)),
        ),
    ]
