# Generated by Django 5.0.7 on 2024-08-31 19:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_medicament_marque_alter_commande_date_heure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_heure',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 31, 19, 8, 15, 67719, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='commande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.commande'),
        ),
    ]
