# Generated by Django 5.0.7 on 2024-08-31 19:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_commande_date_heure_alter_expedition_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_heure',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 31, 19, 20, 37, 698864, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ligne_commande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligne_commande', to='client.commande'),
        ),
    ]
