# Generated by Django 5.0.7 on 2024-09-04 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_commande_date_heure_alter_expedition_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_heure',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 4, 13, 17, 38, 91198, tzinfo=datetime.timezone.utc)),
        ),
    ]
